### ISSUE TITLE
Timelines for milestone

### ISSUE THREAD

**Issue by shivajena** [UBC-MDS/doggodash#55]
- [ ] 16th EOD (tentative) - Completion of new features
- [ ] 17th EOD - python app frontend completion
- [ ] 18th EOD (tentative) - R app deployment completion
